name: Continuous integration

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ructions/toolchain@v2
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Check
        run: cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ructions/toolchain@v2
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Test
        run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ructions/toolchain@v2
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: Format
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ructions/toolchain@v2
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: Clippy
        run: cargo clippy -- -Dwarnings
